### ISSUE TITLE
Socket connection refused issue

### ISSUE THREAD

**Issue by xiasha1988** [FalcoSuessgott/vault-kubernetes-kms#201]
Does anyone met socket connection issue after run for sometime? Errors look like:

"kms plugin failed health check probe" err="rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing: dial unix /opt/kms/vaultkms.socket: connect: connection refused\"" name="vault-kubernetes-kms"

**Comment by xiasha1988** [comment]
I just set -force-socket-overwrite=true, not sure whether works.

**Comment by FalcoSuessgott** [comment]
make sure to mount the path `/opt/kms` of the underlying host: 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: vault-kubernetes-kms
  namespace: kube-system
spec:
  priorityClassName: system-node-critical
  hostNetwork: true # important
  containers:
    - name: vault-kubernetes-kms
      image: falcosuessgott/vault-kubernetes-kms:latest
      command:
        - /vault-kubernetes-kms
        - -vault-address=https://vault.server.de
        - -auth-method=approle
        - -approle-role-id=XXXX
        - -approle-secret-id=XXXX
      volumeMounts:
        - name: kms
          mountPath: /opt/kms
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
      readinessProbe:
        httpGet:
          path: /live
          port: 8080
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2
          memory: 1Gi
  volumes:
    - name: kms
      hostPath:
        path: /opt/kms # important
```
